name: MPI Parallel Sort

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install MPI
        run: |
          sudo apt update
          sudo apt install -y openmpi-bin libopenmpi-dev

      - name: Compile
        run: |
          mpicc parallel_sort.c -o parallel_sort

      - name: Run
        run: |
          mpirun --allow-run-as-root -np 4 ./parallel_sort 16
